VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ShtMain"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True
'===============================================================
' Class ShtMain
'---------------------------------------------------------------
' Created by Julian Turner
' OneSheet Consulting
' Julian.turner@OneSheet.co.uk
'===============================================================
' v1.0.0 - Initial Version
'---------------------------------------------------------------
' Date - 24 Jul 22
'===============================================================

Private Const StrMODULE As String = "ModLibrary"
Option Explicit

'Private Sub BtnNewProjectWF_Click()
'    ModUIScreenCom.ProcessBtnPress enBtnNewProjectWF
'End Sub
